module.exports = {
  caseType: 'role_based_training_assignment', initialState: 'assigned',
  states: ['assigned','content_verified','in_progress','assessed','attested','remediation','compliance_review','closed'],
  createRoles: ['training_admin','compliance_owner'],
  evidenceKinds: ['hris_role_snapshot','curriculum_manifest','content_version','accessibility_result','assessment_attempt','attestation','remediation_record','audit_report'],
  requiredSignals: ['roleVersion','contentVersion','assessmentScore','passingScore','accessibilityStatus','policyVersion'],
  assessmentRoles: ['learner','training_admin','compliance_owner'],
  auditRoles: ['training_admin','compliance_owner'],
  connectorRoles: ['training_admin','compliance_owner'],
  professionalBoundary: 'Training evidence is administrative support, not legal advice; a compliance owner must approve closure.',
  connectors: [
    { name:'lms', purpose:'assignment and attempt synchronization' },
    { name:'hris', purpose:'workforce role snapshots' },
    { name:'identity', purpose:'authoritative workforce identity' },
    { name:'policy_repository', purpose:'versioned approved content' },
    { name:'notification', purpose:'reminders and delivery receipts' },
    { name:'compliance_case', purpose:'approved remediation handoff' },
  ],
  transitions: [
    { from:'assigned', action:'verify_content', to:'content_verified', roles:['training_admin','compliance_owner'], requiresEvidence:true },
    { from:'content_verified', action:'begin', to:'in_progress', roles:['learner'], requiresEvidence:true },
    { from:'in_progress', action:'record_assessment', to:'assessed', roles:['learner','training_admin'], requiresEvidence:true },
    { from:'assessed', action:'attest', to:'attested', roles:['learner'], requiresEvidence:true },
    { from:'assessed', action:'assign_remediation', to:'remediation', roles:['training_admin'], requiresEvidence:true, dualControl:true },
    { from:'remediation', action:'resubmit', to:'assessed', roles:['learner','training_admin'], requiresEvidence:true },
    { from:'attested', action:'submit_compliance_review', to:'compliance_review', roles:['training_admin'], requiresEvidence:true },
    { from:'compliance_review', action:'close', to:'closed', roles:['compliance_owner'], requiresEvidence:true, dualControl:true },
  ],
  assess: x => { const score=Number(x.assessmentScore); const passing=Number(x.passingScore); const valid=Number.isFinite(score)&&Number.isFinite(passing)&&score>=0&&score<=100&&passing>=0&&passing<=100; return { disposition:valid&&score>=passing&&x.accessibilityStatus==='verified'?'eligible_for_attestation':'remediation_required', legalAdvice:null, versions:{role:x.roleVersion,content:x.contentVersion} }; },
};
